In [6]:
import tensorflow as tf
import numpy as np

c = tf.add([1,3],[5,7])
print(c) #tf.Tensor([ 6 10], shape=(2,), dtype=int32)
print(c.numpy(),np.array([[1,2],[3,4]]))

tf.Tensor([ 6 10], shape=(2,), dtype=int32)
[ 6 10] [[1 2]
 [3 4]]


In [7]:
a = tf.constant([1,3],shape=[1,2])
b = tf.constant([5,7], shape=[2,1])
c=tf.matmul(a,b)
print(c.numpy())
print(c.shape)

print( np.array([1,2]).shape) #(2,)




[[26]]
(1, 1)
(2,)


## Test numpy
Numpy tests prerequisites. 

In [8]:
x = np.array([[1,2],[3,4]])
print(x.ndim,x.shape,x.size, x.dtype)
y = x.astype('float') #float64
print(y, y.dtype)

2 (2, 2) 4 int32
[[1. 2.]
 [3. 4.]] float64


In [9]:
l = [1,2,3,4]
print(type(l))
print(type(np.array(l)))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
print(np.vstack([[1,2],[3,4]])) #stack κατά μήκος στήλης (κάτω από το άλλο)
print(np.hstack([[1,2],[3,4]])) #stack κατά μήκος γραμμής (δίπλα από το άλλο)

print(l.copy())


[[1 2]
 [3 4]]
[1 2 3 4]
[1, 2, 3, 4]


In [35]:
a=np.array([0,1,2,3,4])
print(a[1:2])
print(a[-1])
print(a[[0,3]]) #pass list of indices

print(a[np.where(a>2)])

r = np.array(list(2*x for x in a))
print(r)



[1]
4
[0 3]
[3 4]
[0 2 4 6 8]
[[1 2]
 [3 4]]


In [28]:

m = np.array([[1,2],[3,4]])
print(m[np.where(m>1)]) #1D
print(np.where(m>1,m,100)) #replace non-matched values with 100! (could also be np.nan or every other value)

n = np.reshape(m,[4,1])
print(n)

[2 3 4]
[[100   2]
 [  3   4]]
[[1]
 [2]
 [3]
 [4]]


In [45]:
d = np.array(((1,2,10,100,50,60),(3,4,20,200,70,80)))
#print(d.T)
print(np.hsplit(d,2)) #σπάει γραμμές  2 κομμάτια (cut cake vertically)
print(np.vsplit(d,2))

[array([[ 1,  2, 10],
       [ 3,  4, 20]]), array([[100,  50,  60],
       [200,  70,  80]])]
[array([[  1,   2,  10, 100,  50,  60]]), array([[  3,   4,  20, 200,  70,  80]])]


In [64]:
#print(np.array([1,2]*np.array([2,3]))*10) #element wise 

a= np.array([[[0,1],[2,3]],[[10,11],[12,13]]])
print(a, a.shape)
#b = np.array([[[100,0]]])
b = np.array([200,0]) #this works too! -> (2,) -> (1,1,2)
print("b=",b, b.shape)
print()
print(a+b)



[[[ 0  1]
  [ 2  3]]

 [[10 11]
  [12 13]]] (2, 2, 2)
b= [200   0] (2,)

[[[200   1]
  [202   3]]

 [[210  11]
  [212  13]]]


## STATISTICS!!

In [78]:
a = [1,2,3,4]
b = [[1,2],[3,4],[5,6]]
#mean, std, var, sum, cumsum, cumprod, min, max, argmin, argmax, all, any
print(np.mean(a)) #works for lists too
print(np.mean(b)) #flattens the matrix
print(np.mean(b,0)) #μέση τιμή για κάθε στήλη
print(np.mean(b,1)) #μέση τιμή για κάθε γραμμή


2.5
3.5
[3. 4.]
[1.5 3.5 5.5]


In [81]:
b = [[[1,2],[3,4],[5,6]],
    [[7,8],[9,10],[11,12]]]
for i in range(np.array(b).ndim):
    print(np.min(b,i))

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [127]:
a = np.array([[0,1,2], [0,1,2]])
print(np.argmin(a,1)) #removes the  "columns" dimension  

c=np.array([1,2])

print(a.shape)


ind = np.zeros(a.shape[1],dtype= np.int32)
print(ind.shape)

print(np.argmax(a,axis=0, out=ind))
print(ind)


[0 0]
(2, 3)
(3,)
[0 0 0]
[0 0 0]


## Integration tests

In [126]:
x = np.linspace(0,1,num=100)
y = x ** 2
print(np.trapz(y,x))

0.33335033840084355


## All/any functions

In [133]:
x = [1,2,3,0]
print(np.all(x)) #έχει μόνο μη μηδενικές τιμές

x = np.array([1,2,3,0],dtype=np.float16)
print(np.all(x)) #έχει μόνο μη μηδενικές τιμές
print(x)

False
False
[1. 2. 3. 0.]


In [143]:
x = np.array([1,2,3])
print(x*x) #always element-wise multiplication
print(np.dot(x,x))
print(np.matmul(x,x.T)) #same ok

[1 4 9]
14
14


## Metrics

In [16]:
import tensorflow as tf
import numpy as np
import keras.metrics as metrics
y_true = np.array([[0],[1],[1]])
y_pred = np.array([[0.0],[0.9],[1.0]])
m = metrics.Accuracy()
m.update_state(y_true,y_pred)
r = m.result()
print(f'{r.numpy():.1%}')
print(f'{m.total.numpy()}') #total correct count
print(f'{m.count.numpy()}') #all count

print(tf.__version__)

66.7%
2.0
3.0
2.12.0


In [20]:
import tensorflow as tf
import numpy as np
import keras.metrics as metrics
y_true = np.array([[0],[1],[1]])
y_pred = np.array([[0.5],[0.500001],[1.0]])
m = metrics.BinaryAccuracy()
m.update_state(y_true,y_pred)
r = m.result()
print(f'{r.numpy():.1%}')
print(f'{m.total.numpy()}') #total correct count
print(f'{m.count.numpy()}') #all count


100.0%
3.0
3.0


In [30]:
import tensorflow as tf
import numpy as np
import keras.metrics as metrics
y_true = np.array([[0,1,1], [0,1,0]])
y_pred = np.array([[0.1,0.9,0.8], [0.3,0.4,0.3]])
m = metrics.CategoricalAccuracy()
m.update_state(y_true,y_pred)
r = m.result()
print(f'{r.numpy():.1%}')
print(f'{m.total.numpy()}') #total correct count
print(f'{m.count.numpy()}') #all count

100.0%
2.0
2.0


In [42]:
import tensorflow as tf
import numpy as np
import keras.metrics as metrics
y_true = np.array([[1], [2]])
y_pred = np.array([[0.1,0.9,0.8], [0.3,0.3,0.4]])

print(y_true.flatten() == np.argmax(y_pred,axis=1)) #[True True]
print(sum([True,True])) #2
print(True==1) #True

m = metrics.SparseCategoricalAccuracy()
m.update_state(y_true,y_pred)
r = m.result()
print(f'{r.numpy():.1%}')
print(f'{m.total.numpy()}') #total correct count
print(f'{m.count.numpy()}') #all count

[ True  True]
2
True
100.0%
2.0
2.0


In [47]:
import tensorflow as tf
import numpy as np
import keras.metrics as metrics
y_true = np.array([[0,1,0], [0,1,0]])
y_pred = np.array([[0.1,0.9,0.8], [0.1,0.2,0.4]])

m = metrics.TopKCategoricalAccuracy(k=2)
m.update_state(y_true,y_pred)
r = m.result()
print(f'{r.numpy():.1%}')
print(f'{m.total.numpy()}') #total correct count
print(f'{m.count.numpy()}') #all count

50.0%
1.0
2.0
